### ISSUE TITLE
Remove use of go-is-domain, ensure it works with non-ICANN names

### ISSUE THREAD

**Issue by lidel** [dnslink-std/go#4]
```
	isd "github.com/jbenet/go-is-domain"
```

See https://github.com/ipfs/go-ipfs/issues/8060 + PRs (https://github.com/ipfs/go-ipfs/pull/8071 & https://github.com/ipfs/go-namesys/pull/13)

**Comment by martinheidegger** [comment]
Removed a while back in https://github.com/dnslink-std/go/commit/8fbbc59ef18902ebe6f7fb06a8c4ab788e41fc13
